### ISSUE TITLE
Feature requests: source maps, official Webpack loaders

### ISSUE THREAD

**Issue by wyattanderson** [opudalo/wap-css#3]
First off, thank you for this library. It's funny, we discussed building literally exactly this solution at work and then this popped up. Saved us a ton of work. It's fabulous.

Some thoughts, though:
1. Would love to see source map support, especially with Webpack integration.
2. On the subject of Webpack, I'd love to see official loaders with some configurability. Right now, I'm using the ones out of the example repo (which maybe should be consolidated into this one? it has more stars), but they have some issues (don't support source maps, don't have prod/debug support, doesn't quite work with hot reloading).

I'd love to contribute PRs for these if you're open to them.

**Comment by opudalo** [comment]
You welcome.
@wyattanderson yes, please contribution is always welcome.
